name: Build APK (Buildozer)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install apt deps
        run: |
          sudo apt update
          sudo apt install -y git openjdk-11-jdk zip unzip zlib1g-dev \
            libncurses5 libtinfo5 build-essential libffi-dev libssl-dev

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install buildozer==1.7.0 virtualenv

      - name: Create build environment & run Buildozer
        run: |
          # optional: show buildozer version
          buildozer --version || true
          # initialise (if needed) and build debug apk
          # Assumes buildozer.spec already present and main.py at repo root
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-files
          path: bin/*.apk
