name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install cython==0.29.19 buildozer

    - name: Build APK with full log
      run: |
          buildozer -v android debug log_level=2

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
          name: build-logs
          path: .buildozer/android/platform/build*

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-APK
        path: bin/*.apk
